### ISSUE TITLE
Unit Test Build Error in PlatformIO, Windows 10. Error: 'g++' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by azeemshatp** [platformio/platform-native#2] opened 2019-11-06 16:14 UTC
I have an issue running unit test cases in platformIO using VS code in Windows 10 PC.
It throws the below error in the platformIO powershell.
"
Building...
'g++' is not recognized as an internal or external command,
operable program or batch file. ....
"
When I type "g++ --version" here, it doesn't detect g++.  

On the other hand, I can access g++ from the windows command line. It seems a problem with the PIO powershell only. I have already setup the path for minGW64 bin folder under the Windows system variables.
Can someone help to run the test cases, please?

Below is the platformio.ini configuration for the unit test native environment:

[env:unit-test-native]
platform = native
framework =
build_flags =
    -std=gnu++17
    -Wall
    -D LITTLE_ENDIAN
    -D UNIT_TEST
    -D __STDC_FORMAT_MACROS
test_build_project_src = true
lib_ignore = 
extra_scripts =

**Comment by ivankravets** [comment] 2022-05-07 10:45
Duplicate of https://github.com/platformio/platform-native/issues/4

**Closed by ivankravets** 2022-05-07 10:45 UTC
